/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_JNILib */

#ifndef _Included_net_JNILib
#define _Included_net_JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_JNILib
 * Method:    initMatrix
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_net_JNILib_initMatrix
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     net_JNILib
 * Method:    passValue
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_net_JNILib_passValue
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     net_JNILib
 * Method:    decomMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_JNILib_decomMatrix
  (JNIEnv *, jclass);

/*
 * Class:     net_JNILib
 * Method:    LUSolver
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_JNILib_LUSolver
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
