/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_FM3JNILib */

#ifndef _Included_net_FM3JNILib
#define _Included_net_FM3JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_FM3JNILib
 * Method:    runFM3
 * Signature: (I[II)[F
 */
JNIEXPORT jfloatArray JNICALL Java_net_FM3JNILib_runFM3
  (JNIEnv *, jclass, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
